---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubetarget.kubetarget.dev
  resources:
  - virtualtargetdevices
  - virtualtargetproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubetarget.kubetarget.dev
  resources:
  - virtualtargetdevices/finalizers
  - virtualtargetproviders/finalizers
  verbs:
  - update
- apiGroups:
  - kubetarget.kubetarget.dev
  resources:
  - virtualtargetdevices/status
  - virtualtargetproviders/status
  verbs:
  - get
  - patch
  - update
