---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubetarget.dev
  resources:
  - virtualhardwareproviders
  - virtualhardwaretargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubetarget.dev
  resources:
  - virtualhardwareproviders/finalizers
  - virtualhardwaretargets/finalizers
  verbs:
  - update
- apiGroups:
  - kubetarget.dev
  resources:
  - virtualhardwareproviders/status
  - virtualhardwaretargets/status
  verbs:
  - get
  - patch
  - update
