---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.kubetarget.dev
  resources:
  - virtualtargetinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubetarget.dev
  resources:
  - virtualtargetinstances/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubetarget.dev
  resources:
  - virtualtargetinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qemu.kubetarget.dev
  resources:
  - qemutargetproviders
  - qemuvirtualtargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qemu.kubetarget.dev
  resources:
  - qemutargetproviders/finalizers
  - qemuvirtualtargets/finalizers
  verbs:
  - update
- apiGroups:
  - qemu.kubetarget.dev
  resources:
  - qemutargetproviders/status
  - qemuvirtualtargets/status
  verbs:
  - get
  - patch
  - update
