apiVersion: kubetarget.dev/v1alpha1
kind: VirtualTarget
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: virtualtarget-sample
spec:
  targetProviderRef:
    name: corellium-provider
    namespace: default
  type: corellium-device
  config:
    deviceType: "iphone16"
    osVersion: "18.4"
    memory: "4GB"
    cpu: "4"
    storage: "128GB"
    network:
      type: "wifi"
      bandwidth: "100Mbps"
    features:
      - "camera"
      - "gps"
      - "bluetooth"
      - "nfc"
    tags:
      Environment: "development"
      Project: "mobile-testing"