apiVersion: kubetarget.io/v1alpha1
kind: VirtualTarget
metadata:
  name: example-lambda-function
  namespace: default
spec:
  targetProviderRef:
    name: aws-provider
    namespace: default
    kind: TargetProvider
    apiVersion: kubetarget.io/v1alpha1
  type: aws-lambda
  config:
    functionName: "my-example-function"
    runtime: "nodejs18.x"
    handler: "index.handler"
    memorySize: 128
    timeout: 30
    environment:
      variables:
        LOG_LEVEL: "info"
        REGION: "us-west-2"
    tags:
      Environment: "development"
      Project: "example-project" 